### PR TITLE
add support android ashmem

### PR DESCRIPTION
**Pull request by hjanetzek**
snippet taken from
https://github.com/pelya/android-shmem/blob/master/cutils/ashmem-dev.c

### CODE REVIEW

**Comment by dwilliamson** [comment]
This is great, thanks. Can you move the ashmem_create_region function into Remotery.c file and remove the need for the header file?

**Comment by hjanetzek** [comment]
Sure, I had it first included but was not sure where to put their copyright notice.

**Comment by dwilliamson** [comment]
Right above the function is fine as that's what I do some some of the other stuff, e.g. https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L934

**Comment by hjanetzek** [comment]
Thanks. Great tool btw! :)

**Pull request merged**
